### ISSUE TITLE
Doesn't the mission say that there are no settlements near the Alpha base on Zenith, and so no civilians are killed?

### ISSUE THREAD

**Issue by obj-obj** [mathwhiz1212/ES-conscience-plugin#1]
![image](https://github.com/mathwhiz1212/ES-conscience-plugin/assets/57120300/74cd07bb-0032-4f4c-a654-8691ab0402f2)

**Comment by mathwhiz1212** [comment]
It's not as bad as I originally thought, but there is an implication of civilian deaths. Look at the Zenith planet description after the fact:

```
The settlements here were never more than tenuous villages operating on the brink of starvation as they sought to make a living in this icy wilderness. Now, many of them have collapsed due to massive earthquakes that came after the Oathkeepers had the planet bombed to destroy an Alpha base.
```

**Comment by obj-obj** [comment]
Ah, I never actually looked at the planet description after the bombing

**Comment by mathwhiz1212** [comment]
@obj-obj Thank you for the input though.
